config/routes.rb
Rails.application.routes.draw do



  # Routes for the Daily monitoring resource:

  # CREATE
  post("/insert_daily_monitoring", { :controller => "daily_monitorings", :action => "create" })
          
  # READ
  get("/daily_monitorings", { :controller => "daily_monitorings", :action => "index" })
  
  get("/daily_monitorings/:path_id", { :controller => "daily_monitorings", :action => "show" })
  
  # UPDATE
  
  post("/modify_daily_monitoring/:path_id", { :controller => "daily_monitorings", :action => "update" })
  
  # DELETE
  get("/delete_daily_monitoring/:path_id", { :controller => "daily_monitorings", :action => "destroy" })

  #------------------------------

  # Routes for the Hospital resource:

  # CREATE
  post("/insert_hospital", { :controller => "hospitals", :action => "create" })
          
  # READ
  get("/hospitals", { :controller => "hospitals", :action => "index" })
  
  get("/hospitals/:path_id", { :controller => "hospitals", :action => "show" })
  
  # UPDATE
  
  post("/modify_hospital/:path_id", { :controller => "hospitals", :action => "update" })
  
  # DELETE
  get("/delete_hospital/:path_id", { :controller => "hospitals", :action => "destroy" })

  #------------------------------

  # Routes for the Medicine resource:

  # CREATE
  post("/insert_medicine", { :controller => "medicines", :action => "create" })
          
  # READ
  get("/medicines", { :controller => "medicines", :action => "index" })
  
  get("/medicines/:path_id", { :controller => "medicines", :action => "show" })
  
  # UPDATE
  
  post("/modify_medicine/:path_id", { :controller => "medicines", :action => "update" })
  
  # DELETE
  get("/delete_medicine/:path_id", { :controller => "medicines", :action => "destroy" })

  #------------------------------

  # Routes for the Other team resource:

  # CREATE
  post("/insert_other_team", { :controller => "other_teams", :action => "create" })
          
  # READ
  get("/other_teams", { :controller => "other_teams", :action => "index" })
  
  get("/other_teams/:path_id", { :controller => "other_teams", :action => "show" })
  
  # UPDATE
  
  post("/modify_other_team/:path_id", { :controller => "other_teams", :action => "update" })
  
  # DELETE
  get("/delete_other_team/:path_id", { :controller => "other_teams", :action => "destroy" })

  #------------------------------

  # Routes for the Nurse resource:

  # CREATE
  post("/insert_nurse", { :controller => "nurses", :action => "create" })
          
  # READ
  get("/nurses", { :controller => "nurses", :action => "index" })
  
  get("/nurses/:path_id", { :controller => "nurses", :action => "show" })
  
  # UPDATE
  
  post("/modify_nurse/:path_id", { :controller => "nurses", :action => "update" })
  
  # DELETE
  get("/delete_nurse/:path_id", { :controller => "nurses", :action => "destroy" })

  #------------------------------

  # Routes for the Doctor resource:

  # CREATE
  post("/insert_doctor", { :controller => "doctors", :action => "create" })
          
  # READ
  get("/doctors", { :controller => "doctors", :action => "index" })
  
  get("/doctors/:path_id", { :controller => "doctors", :action => "show" })
  
  # UPDATE
  
  post("/modify_doctor/:path_id", { :controller => "doctors", :action => "update" })
  
  # DELETE
  get("/delete_doctor/:path_id", { :controller => "doctors", :action => "destroy" })

  #------------------------------

  # Routes for the Patient resource:

  # CREATE
  post("/insert_patient", { :controller => "patients", :action => "create" })
          
  # READ
  get("/patients", { :controller => "patients", :action => "index" })
  
  get("/patients/:path_id", { :controller => "patients", :action => "show" })
  
  # UPDATE
  
  post("/modify_patient/:path_id", { :controller => "patients", :action => "update" })
  
  # DELETE
  get("/delete_patient/:path_id", { :controller => "patients", :action => "destroy" })

  #------------------------------

  resources :todos
  #get 'welcome/index'
  root to: 'welcome#index'
  
  #get("/path1", { :controller => "medicines", :action => "create" })

  #get("/path2", { :controller => "daily_monitorings", :action => "index" })

  #get("path3", { :controller => "employees", :action => "index" })

   get("daily_monitorings", { :controller => "daily_monitorings", :action => "index" })
end

app/models/todo.rb
# == Schema Information
#
# Table name: todos
#
#  id          :integer          not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Todo < ApplicationRecord
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:title, :description)
    end
end

app/views/todos/_form.html.erb
<%= simple_form_for @todo, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%#= error_span(@todo[:title]) %>
  <%= f.input :description %>
  <%#= error_span(@todo[:description]) %>

  <%= f.button :submit, :class => 'btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                todos_path, :class => 'btn btn-default' %>
<% end %>

app/views/todos/edit.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/index.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= link_to todo.id, todo_path(todo) %></td>
        <td><%= todo.title %></td>
        <td><%= todo.description %></td>
        <td><%=l todo.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      todo_path(todo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_todo_path(todo), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      todo_path(todo),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_todo_path,
            :class => 'btn btn-primary' %>

app/views/todos/new.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/todos/show.html.erb
<%- model_class = Todo -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @todo.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @todo.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              todos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_todo_path(@todo), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              todo_path(@todo),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>